name: Update Flake inputs
on:
  schedule:
    - cron: "0 0 * * 0" # runs weekly on Sunday at 00:00
  workflow_dispatch: # allows manual triggering

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
        with:
          extra_nix_config: |
            experimental-features = flakes nix-command
            flake-registry = https://github.com/c4f3z1n/nix-registry/raw/main/registry.json
            nix-path = nixpkgs=flake:nixpkgs
      - run: nix flake update
      - run: nix fmt

      # - id: update
      #   uses: determinatesystems/update-flake-lock@v21
      #   with:
      #     nix-options: --flake-registry https://github.com/c4f3z1n/nix-registry/raw/main/registry.json
      #     pr-labels: dependencies
      #     pr-title: Update flake.lock
      #     token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
